version: '2'

services:
    nextjs-workshop:
        image: registry.thinknet.co.th/sredev/node:8.9
        command: ['/bin/sh', '-c', 'yarn && yarn dev']
        environment:
                NODE_ENV: dev
                NODE_PORT: 3000
        ports:
            - 3000:3000
        volumes:
            - .:/usr/src/app
            
networks:
    default:
        external:
            name: workshop-network